name: Build docs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install docs dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-dev.txt
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html ./source ./build"
    - name: rsync docs
      uses: burnett01/rsync-deployments@master
      with:
        switches: -vzr
        path: docs/build/html
        remote_path: /home/jacq-convokit/convokit/documentation
        remote_host: jacqueline.infosci.cornell.edu
        remote_user: $${{ secrets.ZISSOU_USER }}
        remote_key: $${{ secrets.ZISSOU_KEY }}
