name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        mongodb-version: [5.0.2]
        storage-version: [mem, db]
      max-parallel: 1
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install .
        python -m spacy download en_core_web_sm
    - name: Set storage mode
      run: |
        export CONVOKIT_STORAGE_MODE=${{ matrix.storage-version }}
    - name: Run tests
      run: |
        python convokit/tests/run_all_tests.py
