name: Sync download_config.json

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync download config
      uses: burnett01/rsync-deployments@master
      with:
        switches: -vzr
        path: download_config.json
        remote_path: ${{ secrets.DEPLOY_DOCS_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
