name: Test Jupyter notebooks

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install convokit[craft]
        python -m spacy download en_core_web_sm
        python -m pip install -r requirements-dev.txt
    - name: Run notebooks
      run: |
        pytest --nbmake --nbmake-timeout=3000 -n=auto --full-trace examples/**/*.ipynb
        pytest --nbmake --nbmake-timeout=3000 -n=auto --full-trace examples/*.ipynb
